### ISSUE TITLE
approval mail not necessary if you have approval rights

### ISSUE THREAD

**Issue by rallek** [zikula-modules/News#146]
If I add a new message to news and approve it directly I do get an email where I am informed that I have approved my message. That is not necessary.

**Comment by Guite** [comment]
You are hitting the edge case that the editor and (the only) moderator is the same person.
But there could be other moderators; in that case it would be reasonable to notify them as well.

**Comment by Guite** [comment]
For clarification: this is default behaviour of the generator. At the configuration page a user group is selected as moderation group. For each editor change a notification mail is sent to all moderators. For each moderator change a notification is sent to the editor.
If there is anything to be changed that should be done in MOST centrally I guess. But I am a bit unsure whether we should change this because

> But there could be other moderators; in that case it would be reasonable to notify them as well.

Opinions? @craigh @gfr

**Comment by craigh** [comment]
I am also unsure.

**Comment by rallek** [comment]
My proposal:
![grafik](https://user-images.githubusercontent.com/935250/87290990-ffc41800-c4fe-11ea-84bc-6c4eaa82a2ae.png)
If you have the permission to **approve** no mail will be send. That was the behavior in the old news module I guess.

But I can live with it as it is. I thought it was different in the past (at least for my zk1.5 site it is different)

**Comment by Guite** [comment]
Intermediate results after a phone call:

1. Ralf is going to do some more tests with having in mind how the workflows and notifications are designed (mails between creators and moderators). Also he will carefully check which mails he receives when (mail to creator vs. mail to moderator).

2. It would be possible to suppress the notification (all notifications) for the creator if this user has approve permissions. This would be a general enhancement in the generator.

**Comment by Guite** [comment]
Closing here because this will become available automatically after the feature has been included in the generator.
